// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Car struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type CreateCarInput struct {
	Name *string `json:"name"`
}
